---
 # file is parsed by inner-most keys only
 data:
     #data_file: "data/intervention_8160.csv"
     data_file: "data/test_240.csv"
     #data_file: "data/test_real.csv"
     debug: False
     batch_size: 16  # 16 for train, 1 for test
     fci_vars: 5
     fci_batches: 10
     fci_batches_inference: 100
     fci_batch_size: 500
     num_workers: 40
     num_io_workers: 40
     accumulate_batches: 1
     log_frequency: 10
     #results_file: "results/results_fci_target_ax1.pkl"
     #results_file: "results/results_240_ax.pkl"
     #results_file: "results/axial_reproduce.pkl"
     results_file: "results/axial_cov_lin.pkl"
     use_learned_sampler: False
 model:
     algorithm: "fci"
     num_vars: 1000
     model: "joint"
     num_edge_types: 8
     embed_dim: 64
     transformer_num_layers: 4
     target_transformer_num_layers: 1
     n_heads: 8
     ffn_embed_dim: 8
 train:
     run_name: causal-target
     patience: 50
     epochs: 10000
     min_epochs: 50
     lr: 1.e-4
     weight_decay: 1.e-5
     metric: "Val/auprc"
